// <auto-generated />
using System;
using FoodPlan.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodPlan.DataAccess.Migrations
{
    [DbContext(typeof(PlanDbContext))]
    [Migration("20260425084055_Inital")]
    partial class Inital
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DailyMealMeal", b =>
                {
                    b.Property<Guid>("BreakfastId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DailyMealId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BreakfastId", "DailyMealId");

                    b.HasIndex("DailyMealId");

                    b.ToTable("DailyMealBreakfast", (string)null);
                });

            modelBuilder.Entity("DailyMealMeal1", b =>
                {
                    b.Property<Guid>("DailyMeal1Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LunchId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DailyMeal1Id", "LunchId");

                    b.HasIndex("LunchId");

                    b.ToTable("DailyMealLunch", (string)null);
                });

            modelBuilder.Entity("DailyMealMeal2", b =>
                {
                    b.Property<Guid>("DailyMeal2Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DinnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DailyMeal2Id", "DinnerId");

                    b.HasIndex("DinnerId");

                    b.ToTable("DailyMealDinner", (string)null);
                });

            modelBuilder.Entity("DailyMealMeal3", b =>
                {
                    b.Property<Guid>("DailyMeal3Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SnacksId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DailyMeal3Id", "SnacksId");

                    b.HasIndex("SnacksId");

                    b.ToTable("DailyMealSnacks", (string)null);
                });

            modelBuilder.Entity("FoodPlan.DataAccess.Entities.DailyMeal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid?>("MealPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalCalories")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MealPlanId");

                    b.ToTable("DailyMeals");
                });

            modelBuilder.Entity("FoodPlan.DataAccess.Entities.Meal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Calories")
                        .HasColumnType("float");

                    b.Property<Guid>("FoodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("FoodPlan.DataAccess.Entities.MealPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvoidTags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DietStyle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NumberOfDays")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TargetDailyCalories")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("MealPlans");
                });

            modelBuilder.Entity("DailyMealMeal", b =>
                {
                    b.HasOne("FoodPlan.DataAccess.Entities.Meal", null)
                        .WithMany()
                        .HasForeignKey("BreakfastId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodPlan.DataAccess.Entities.DailyMeal", null)
                        .WithMany()
                        .HasForeignKey("DailyMealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DailyMealMeal1", b =>
                {
                    b.HasOne("FoodPlan.DataAccess.Entities.DailyMeal", null)
                        .WithMany()
                        .HasForeignKey("DailyMeal1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodPlan.DataAccess.Entities.Meal", null)
                        .WithMany()
                        .HasForeignKey("LunchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DailyMealMeal2", b =>
                {
                    b.HasOne("FoodPlan.DataAccess.Entities.DailyMeal", null)
                        .WithMany()
                        .HasForeignKey("DailyMeal2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodPlan.DataAccess.Entities.Meal", null)
                        .WithMany()
                        .HasForeignKey("DinnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DailyMealMeal3", b =>
                {
                    b.HasOne("FoodPlan.DataAccess.Entities.DailyMeal", null)
                        .WithMany()
                        .HasForeignKey("DailyMeal3Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodPlan.DataAccess.Entities.Meal", null)
                        .WithMany()
                        .HasForeignKey("SnacksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FoodPlan.DataAccess.Entities.DailyMeal", b =>
                {
                    b.HasOne("FoodPlan.DataAccess.Entities.MealPlan", null)
                        .WithMany("Days")
                        .HasForeignKey("MealPlanId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FoodPlan.DataAccess.Entities.MealPlan", b =>
                {
                    b.Navigation("Days");
                });
#pragma warning restore 612, 618
        }
    }
}
